### ISSUE TITLE
errore sul prompt

### ISSUE THREAD

**Issue by ValeriaCom** [marcobonaccorso/CrudAng#1]
Prof, ho tirato giù il commit di Lillo e mi da questo errore sul prompt.
![Catturacrudang](https://user-images.githubusercontent.com/78487304/108871455-7975c580-75f9-11eb-941d-e85398e0fde1.PNG)

**Comment by luca-lezzerini** [comment]
Vada nella cartella di progetto sul terminale e dia npm update

Aspetti che finisca l'aggiornamento e riprovi.

A me funziona.

**Comment by ValeriaCom** [comment]
Risolto, grazie.
